routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('movement', 'MovementController');
    Route::resource('compras', 'PurchaseOrderController');
    Route::resource('productos', 'ProductController');
    Route::resource('comprasDetalle', 'PurchaseOrderDetailController');
});

resources/views/includes/aside.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane active" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:;">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="pull-right-container">
                <span class="label label-danger pull-right">70%</span>
              </span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>

resources/views/includes/content-header.blade.php
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    @yield('title')
    <small>@yield('description')</small>
  </h1>
  <!--<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
    <li class="active">Here</li>
  </ol>-->
</section>

resources/views/includes/content.blade.php
<!-- Main content -->
<section class="content">
  <div id="flash-msg">
      @include('flash::message')
  </div>
  @yield('content')
  @stack('scripts')

  <script>
      $(function () {
          // flash auto hide
          $('#flash-msg .alert').not('.alert-danger, .alert-important').delay(6000).slideUp(500);
      })
  </script>
</section>

resources/views/includes/header.blade.php
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>HOTEL</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b></span>
  </a>
  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">




        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="{{ asset("/admin-lte/dist/img/user2-160x160.jpg") }}" class="user-image" alt="User Image">
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">{{ Auth::user()->name }}</span>
          </a>
          <ul class="dropdown-menu">
            @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
                <li><a href="{{ route('register') }}">Register</a></li>
            @else

            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="{{ asset("/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image">

              <p>
                {{ Auth::user()->name }}
                <span class="label label-success">{{ Auth::user()->roles->pluck('name')->first() }}</span>
              </p>
            </li>
            <!-- Menu Body
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            @endif
            <!-- Menu Footer-->
            <li class="user-footer">
              <!--<div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>-->
              <div class="text-center">
                <a  href="{{ route('logout') }}"
                    onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                    class="btn btn-default btn-flat">Sign out
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
              </div>
            </li>
          </ul>
        </li>

      </ul>
    </div>
  </nav>
</header>

resources/views/includes/main-footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">

  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2017 <a href="#">Geek2Web</a>.</strong> All rights reserved.
</footer>

resources/views/includes/menu.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset("/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>Juan Carlos</p>
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Menu</li>
      <!-- Optionally, you can add icons to the links -->
      <li class="{{ Request::is('home*') ? 'active' : '' }}"><a href="{{ route('home')}}"><i class="fa fa-link"></i> <span>Dashboard</span></a></li>
      @if (Auth::check())
          <li class="treeview {{ Request::is('compras*') ? 'active' : '' }}">
            <a href="#"><i class="text-info fa fa-fw fa-list"></i> <span>Compras</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="{{ route('compras.index')}}"><i class="text-info fa fa-fw fa-list"></i> Lista Compras</a></li>
              <li><a href="{{ route('compras.create')}}"><i class="text-info fa fa-fw fa-arrow-circle-right"></i> Crear Compra</a></li>
            </ul>
          </li>
          <li class="treeview {{ Request::is('movements*') ? 'active' : '' }}">
            <a href="#"><i class="text-info fa fa-fw fa-list"></i> <span>Movimientos</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="{{ route('movement.index')}}"><i class="text-info fa fa-fw fa-list"></i> Lista Movimientos</a></li>
              <li><a href="{{ route('movement.create')}}"><i class="text-info fa fa-fw fa-arrow-circle-right"></i> Crear Entrada</a></li>
              <li><a href="{{ route('movement.create')}}"><i class="text-info fa fa-fw fa-arrow-circle-left"></i> Crear Salida</a></li>
            </ul>
          </li>
          <li class="treeview {{ Request::is('movements*') ? 'active' : '' }}">
            <a href="#"><i class="text-info fa fa-fw fa-line-chart"></i> <span>Reportes</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="{{ route('movement.index')}}"><i class="text-info fa fa-fw fa-list"></i> Reporte de Entradas</a></li>
              <li><a href="{{ route('movement.create')}}"><i class="text-info fa fa-fw fa-arrow-circle-right"></i> Reporte de Salidas</a></li>
            </ul>
          </li>
          @can('view_users')
              <li class="treeview {{ Request::is('users*') ? 'active' : '' }}">
                <a href="#"><i class="text-info glyphicon glyphicon-user"></i> <span>Users</span>
                  <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                  </span>
                </a>
                <ul class="treeview-menu">
                  <li><a href="{{ route('users.index')}}">Lista</a></li>
                  <li><a href="{{ route('users.create')}}">Crear Nuevo</a></li>
                </ul>
              </li>
          @endcan

          @can('view_posts')
              <!-- <li class="{{ Request::is('posts*') ? 'active' : '' }}">
                  <a href="{{ route('posts.index') }}">
                      <i class="text-success glyphicon glyphicon-text-background"></i> <span>Posts</span>
                  </a>
              </li>-->
          @endcan
          @can('view_roles')
            <li class="{{ Request::is('roles*') ? 'active' : '' }}">
                <a href="{{ route('roles.index') }}">
                    <i class="text-danger glyphicon glyphicon-lock"></i> <span>Roles</span>
                </a>
            </li>
          @endcan

      @endif
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>